apiVersion: crds.kloudlite.io/v1
kind: Workspace
metadata:
  name: sample
  namespace: default
spec:
  state: "ON"
  nodeName: "worker-2"
  serviceAccountName: "kloudlite"
  enableCodeServer: false
  enableVSCodeServer: false
  enableTTYD: false
  enableJupyterNotebook: false
  imagePullPolicy: IfNotPresent
  router:
    ingressClass: "nginx"
    domains:
      - "sample.demo.kloudlite.io"
    https:
      enabled: true
    routes:
      - app: sample
        path: "/"
        port: 3000
