{{- $name := printf "%s-gateway" .Release.Name -}}
{{- $namespace := .Release.Namespace -}}
{{- $image := .Values.image.gateway -}}
{{- $tag := .Values.image.tag -}}
{{- $pullPolicy := .Values.image.pullPolicy -}}
{{- $resources := .Values.resources -}}
{{- $server_config := .Values.server_config -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  labels: &labels
    kloudlite.io/cluster-gateway: "true"
    kloudlite.io/pod-type: {{ $name }}
  name: {{ $name }}
  namespace: {{ $namespace }}
spec:
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  selector:
    matchLabels: *labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels: *labels
    spec:
      containers:
      - image: {{ $image }}:{{ $tag }}
        imagePullPolicy: {{ $pullPolicy }}
        env:
        - name: ADDR
          value: :3000
        - name: CONFIG_PATH
          value: /tmp/server-config.yml
        - name: ENDPOINT
          value: {{ $name }}.{{ $namespace }}.svc.cluster.local:8080
        name: gateway
        ports:
        - containerPort: 8080
          protocol: UDP
        - containerPort: 3000
          protocol: TCP
        resources: {{ $resources | toJson }}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - SYS_MODULE
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /lib/modules
          name: host-volumes
        - mountPath: /tmp/server-config.yml
          name: gateway-configs
          subPath: server-config.yml
      dnsPolicy: Default
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - operator: Exists
      volumes:
      - name: gateway-configs
        secret:
          defaultMode: 420
          items:
          - key: server-config
            path: server-config.yml
          secretName: {{ $name }}-configs
      - hostPath:
          path: /lib/modules
          type: Directory
        name: host-volumes
---

apiVersion: v1
stringData:
  server-config: |+
    {{ $server_config | toYaml | nindent 4 }}

kind: Secret
metadata:
  name: {{ $name }}-configs
  namespace: {{ $namespace }}
type: Opaque
---

apiVersion: v1
kind: Service
metadata:
  labels: &labels
    kloudlite.io/cluster-gateway: "true"
    kloudlite.io/pod-type: {{ $name }}
  name: {{ $name }}
  namespace: {{ $namespace }}
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector: *labels

--- 
apiVersion: v1
kind: Service
metadata:
  labels: &labels
    kloudlite.io/cluster-gateway: "true"
    kloudlite.io/pod-type: {{ $name }}
  name: {{ $name }}-external
  namespace: {{ $namespace }}
spec:
  ports:
  - port: 8080
    protocol: UDP
    targetPort: 8080
  selector: *labels
  type: NodePort
