//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package operator

import (
	"github.com/kloudlite/operator/apis/common-types"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *common_types.Check) DeepCopyInto(out *common_types.Check) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Check.
func (in *common_types.Check) DeepCopy() *common_types.Check {
	if in == nil {
		return nil
	}
	out := new(common_types.Check)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *common_types.Status) DeepCopyInto(out *common_types.Status) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]common_types.ResourceRef, len(*in))
		copy(*out, *in)
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = (*in).DeepCopy()
	}
	if in.Checks != nil {
		in, out := &in.Checks, &out.Checks
		*out = make(map[string]common_types.Check, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LastReconcileTime != nil {
		in, out := &in.LastReconcileTime, &out.LastReconcileTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Status.
func (in *common_types.Status) DeepCopy() *common_types.Status {
	if in == nil {
		return nil
	}
	out := new(common_types.Status)
	in.DeepCopyInto(out)
	return out
}
