kind: Namespace
apiVersion: v1
metadata:
  name: cluster-vpn-test

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kl-agents
  namespace: cluster-vpn-test
  labels: &labels
    kloudlite.io/cluster-agent: "true"
    kloudlite.io/pod-type: kl-cluster-agent
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      containers:
      - image: ghcr.io/kloudlite/operator/components/multi-cluster-agent:v1.0.5-nightly
        imagePullPolicy: Always
        name: agent
        env:
        - name: SERVER_ADDR
          value: http://kl-gateway-api.cluster-vpn-test.svc.cluster.local:3000
        - name: KUBE_DNS_IP
          value: 10.43.0.10
        - name: MY_IP_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          limits:
            memory: 20Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - SYS_MODULE
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /lib/modules
          name: host-volumes
      dnsPolicy: Default
      securityContext: {}
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      hostNetwork: true
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /lib/modules
          type: Directory
        name: host-volumes
