kind: Namespace
apiVersion: v1
metadata:
  name: cluster-vpn-test

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels: &labels
    kloudlite.io/cluster-gateway: "true"
    kloudlite.io/pod-type: kl-cluster-gateway
  name: kl-gateway
  namespace: cluster-vpn-test
spec:
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  selector:
    matchLabels: *labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels: *labels
    spec:
      containers:
      - image: ghcr.io/kloudlite/operator/components/multi-cluster-gateway:v1.0.5-nightly
        imagePullPolicy: Always
        env:
        - name: ADDR
          value: :3000
        - name: CONFIG_PATH
          value: /tmp/server-config.yml
        - name: ENDPOINT
          value: kl-gateway.cluster-vpn-test.svc.cluster.local:8080
        name: gateway
        ports:
        - containerPort: 8080
          protocol: UDP
        - containerPort: 3000
          protocol: TCP
        resources:
          limits:
            memory: 50Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - SYS_MODULE
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /lib/modules
          name: host-volumes
        - mountPath: /tmp/server-config.yml
          name: gateway-configs
          subPath: server-config.yml
      dnsPolicy: Default
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - operator: Exists
      volumes:
      - name: gateway-configs
        secret:
          defaultMode: 420
          items:
          - key: server-config
            path: server-config.yml
          secretName: gateway-configs
      - hostPath:
          path: /lib/modules
          type: Directory
        name: host-volumes
---

apiVersion: v1
stringData:
  server-config: |+
    privateKey: wrhprQu1BRNhpNIe8Skjh+aKlPJrhqztD0xBBvkh+uk=
    ip: 10.13.0.1/32

kind: Secret
metadata:
  name: gateway-configs
  namespace: cluster-vpn-test
type: Opaque
---

apiVersion: v1
kind: Service
metadata:
  labels: &labels
    kloudlite.io/cluster-gateway: "true"
    kloudlite.io/pod-type: kl-cluster-gateway
  name: kl-gateway-api
  namespace: cluster-vpn-test
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector: *labels

--- 
apiVersion: v1
kind: Service
metadata:
  labels: &labels
    kloudlite.io/cluster-gateway: "true"
    kloudlite.io/pod-type: kl-cluster-gateway
  name: kl-gateway
  namespace: cluster-vpn-test
spec:
  ports:
  - port: 8080
    protocol: UDP
    targetPort: 8080
  selector: *labels
  type: NodePort
