image:
  agent: ghcr.io/kloudlite/operator/components/multi-cluster-agent
  gateway: ghcr.io/kloudlite/operator/components/multi-cluster-gateway
  tag: v1.0.5-nightly
  pullPolicy: Always

coredns_svc_ip: 10.43.0.10
resources:
  limits:
    cpu: 50m
    memory: 50Mi
  requests:
    cpu: 25m
    memory: 25Mi

nodeport: ""
server_config:
  # privateKey: wrhprQu1BRNhpNIe8Skjh+aKlPJrhqztD0xBBvkh+uk=
  # ip: 10.13.0.1/32
  # peers:
  #   - ip: ""
  #     publicKey: ""
  #     endpoint: ""
  #     allowedIPs: ""
